INSERT INTO public.bottom_bracket (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_length, bottom_bracket_shell_diameter, insert_type, shell_width, type) VALUES (1, 'Shimano', null, null, true, 'BB-MT800', 'MT800', 'bottomBracket', 'BBR-SHIMN-MT800', 'MTB', 'XT', 0.082, null, null, 24, null, null, 'threaded', '68,73', 'integrated');
INSERT INTO public.bottom_bracket (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_length, bottom_bracket_shell_diameter, insert_type, shell_width, type) VALUES (2, 'Shimano', null, null, true, 'BB-MT800-P', 'MT800-P', 'bottomBracket', 'BBR-SHIMN-MT800-P', 'MTB', 'XT', 0.062, null, null, 24, null, null, 'press-fit', null, 'integrated');

INSERT INTO public.brake_rotor (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, pad_type) VALUES (1, 'Shimano', null, null, true, 'RT-MT800', 'MT800', 'brakeRotor', 'DSC-SHIMN-MT800-203', 'MTB', 'XT', 0.163, null, null, 203, null);
INSERT INTO public.brake_rotor (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, pad_type) VALUES (2, 'Shimano', null, null, true, 'RT-MT800', 'MT800', 'brakeRotor', 'DSC-SHIMN-MT800-180', 'MTB', 'XT', 0.132, null, null, 180, null);
INSERT INTO public.brake_rotor (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, pad_type) VALUES (3, 'Shimano', null, null, true, 'RT-MT800', 'MT800', 'brakeRotor', 'DSC-SHIMN-MT800-160', 'MTB', 'XT', 0.108, null, null, 160, null);
INSERT INTO public.brake_rotor (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, pad_type) VALUES (4, 'Shimano', null, null, true, 'RT-MT800', 'MT800', 'brakeRotor', 'DSC-SHIMN-MT800-140', 'MTB', 'XT', 0.088, null, null, 140, null);

INSERT INTO public.cassette (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, biggest, freewheel_body, smallest, speeds) VALUES (1, 'Shimano', null, null, true, 'CS-M8100-12', 'M8100-12', 'cassette', 'CST-SHIMN-M810012-45', 'MTB', 'XT', 0.461, null, null, 45, 'micro-spline', 10, 12);
INSERT INTO public.cassette (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, biggest, freewheel_body, smallest, speeds) VALUES (2, 'Shimano', null, null, true, 'CS-M8100-12', 'M8100-12', 'cassette', 'CST-SHIMN-M810012-51', 'MTB', 'XT', 0.470, null, null, 51, 'micro-spline', 10, 12);

INSERT INTO public.chain (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, speeds) VALUES (1, 'Shimano', null, null, true, 'CN-M8100', 'M8100', 'chain', 'CHN-SHIMN-M8100', 'MTB', 'XT', 0.252, null, null, 12);

INSERT INTO public.chainring (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arms_and_type, pcd, speeds, teeth_number, type) VALUES (3, 'Shimano', null, null, true, 'SM-CRM85', 'CRM85', 'chainring', 'CHR-SHIMN-CRM85-32', 'MTB', 'XT', 0.115, null, null, 'direct mount shimano', null, 12, 32, null);
INSERT INTO public.chainring (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arms_and_type, pcd, speeds, teeth_number, type) VALUES (1, 'Shimano', null, null, true, 'SM-CRM85', 'CRM85', 'chainring', 'CHR-SHIMN-CRM85-36', 'MTB', 'XT', 0.146, null, null, 'direct mount shimano', null, 12, 36, null);
INSERT INTO public.chainring (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arms_and_type, pcd, speeds, teeth_number, type) VALUES (5, 'Shimano', null, null, true, 'SM-CRM85', 'CRM85', 'chainring', 'CHR-SHIMN-CRM85-28', 'MTB', 'XT', 0.103, null, null, 'direct mount shimano', null, 12, 28, null);
INSERT INTO public.chainring (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arms_and_type, pcd, speeds, teeth_number, type) VALUES (2, 'Shimano', null, null, true, 'SM-CRM85', 'CRM85', 'chainring', 'CHR-SHIMN-CRM85-34', 'MTB', 'XT', 0.128, null, null, 'direct mount shimano', null, 12, 34, null);
INSERT INTO public.chainring (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arms_and_type, pcd, speeds, teeth_number, type) VALUES (4, 'Shimano', null, null, true, 'SM-CRM85', 'CRM85', 'chainring', 'CHR-SHIMN-CRM85-30', 'MTB', 'XT', 0.117, null, null, 'direct mount shimano', null, 12, 30, null);

INSERT INTO public.crank (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, arm_length, arms_and_type, axle_diameter, cartridge_type, chain_line, number_of_gears, pcd_big, pcd_small, q_factor, speeds, big_gear_id, medium_gear_id, small_gear_id, big_gear_model, medium_gear_model, small_gear_model) VALUES (1, 'Shimano', null, null, true, 'FC-M8100-1', 'M8100-1', 'crank', 'CRK-SHIMN-M8100-1', 'MTB', 'XT', 0.505, null, null, '165,170,175,180', 'direct mount shimano', null, null, 52, 1, null, null, 172, 12, null, null, null, null, null, 'SM-CRM85');

INSERT INTO public.fork (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, adjustments, axle_size, axle_type, brake_type, disc_mount, fork_offset, head_tube_bottom_diameter, head_tube_length, head_tube_top_diameter, material, remote_lockout, spring, suspension_type, travel, uppers_size, wheel, damper) VALUES (1, 'Manitou', null, null, true, null, 'Markhor', 'fork', 'FRK-MANITOU-MARKHOR-26-100', 'XC', 'Markhor', 1.656, null, null, null, '9x100', 'QR', 'disc', 'PM', null, 28.6, null, 28.6, null, null, 'TS Air', 'AIR', 100, '30', '26', 'Kwik Toggle/TPC');
INSERT INTO public.fork (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, adjustments, axle_size, axle_type, brake_type, disc_mount, fork_offset, head_tube_bottom_diameter, head_tube_length, head_tube_top_diameter, material, remote_lockout, spring, suspension_type, travel, uppers_size, wheel, damper) VALUES (2, 'Manitou', null, null, true, null, 'Markhor', 'fork', 'FRK-MANITOU-MARKHOR-27-100', 'XC', 'Markhor', 1.677, null, null, null, '9x100', 'QR', 'disc', 'PM', null, 28.6, null, 28.6, null, null, 'TS Air', 'AIR', 100, '30', '27', 'Kwik Toggle/TPC');
INSERT INTO public.fork (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, adjustments, axle_size, axle_type, brake_type, disc_mount, fork_offset, head_tube_bottom_diameter, head_tube_length, head_tube_top_diameter, material, remote_lockout, spring, suspension_type, travel, uppers_size, wheel, damper) VALUES (3, 'Manitou', null, null, true, null, 'Markhor', 'fork', 'FRK-MANITOU-MARKHOR-29-100', 'XC', 'Markhor', 1.696, null, null, null, '9x100', 'QR', 'disc', 'PM', null, 28.6, null, 28.6, null, null, 'TS Air', 'AIR', 100, '30', '29', 'Kwik Toggle/TPC');

INSERT INTO public.frame (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, bottom_bracket_size, bottom_bracket_type, bottom_head_set_diameter, brake_type, disc_brake_mount, fork_tube_type, has_damper, headset_type, material, rear_wheel_axle_size, seatpost_caliper_diameter, seatpost_size, size, size_unit, size_value, top_head_set_diameter, wheel_size) VALUES (1, 'Kross', null, null, true, null, 'Vento', 'frame', null, null, null, null, '2021', null, null, null, null, null, null, null, false, null, 'aluminium', null, null, null, null, null, null, null, '28');
INSERT INTO public.frame (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, bottom_bracket_size, bottom_bracket_type, bottom_head_set_diameter, brake_type, disc_brake_mount, fork_tube_type, has_damper, headset_type, material, rear_wheel_axle_size, seatpost_caliper_diameter, seatpost_size, size, size_unit, size_value, top_head_set_diameter, wheel_size) VALUES (300, 'Trek', null, null, true, null, 'Domane', 'frame', 'FRM-TREK-DOMANE-AL5-2021', 'gravel', 'AL 5 DISC', null, '2021', null, '68', 'threaded', 38.1, 'disc', 'flat mount', 'tapered', false, 'integrated', 'aluminium', '142x12', null, 27.2, '[44,49,52,54,56,58,61]', 'MM', null, 28.6, '28');

INSERT INTO public.front_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cable_route_type, cage, capacity, chain_line, chainstay_angle, gear_max_difference, gears, max_big_gear, min_big_gear, mount, speeds) VALUES (1, 'Shimano', 'chainline 48.8 (142 mm O.L.D.) | 51.8 (148 mm O.L.D.)', null, true, 'FD-M8100-D', 'M8100-D', 'frontDerailleur', 'FDR-SHIMN-M8100D', 'MTB', 'XT', 0.135, null, null, 'middle', 'side-swing', 10, 48.8, '66-69', null, 2, 38, 36, 'direct type-D', 12);
INSERT INTO public.front_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cable_route_type, cage, capacity, chain_line, chainstay_angle, gear_max_difference, gears, max_big_gear, min_big_gear, mount, speeds) VALUES (2, 'Shimano', 'chainline 48.8 (142 mm O.L.D.) | 51.8 (148 mm O.L.D.)', null, true, 'FD-M8100-E', 'M8100-E', 'frontDerailleur', 'FDR-SHIMN-M8100E', 'MTB', 'XT', 0.106, null, null, 'middle', 'side-swing', 10, 48.8, '66-69', null, 2, 38, 36, 'direct type-D', 12);
INSERT INTO public.front_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cable_route_type, cage, capacity, chain_line, chainstay_angle, gear_max_difference, gears, max_big_gear, min_big_gear, mount, speeds) VALUES (3, 'Shimano', 'chainline 48.8 (142 mm O.L.D.) | 51.8 (148 mm O.L.D.)', null, true, 'FD-M8100-M', 'M8100-M', 'frontDerailleur', 'FDR-SHIMN-M8100M', 'MTB', 'XT', 0.114, null, null, 'middle', 'side-swing', 10, 48.8, '66-69', null, 2, 38, 36, 'clamp 31.8, 34.9', 12);

INSERT INTO public.headset (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, bottom_frame_diameter, bottom_head_tube_diameter, top_frame_diameter, top_head_tube_diameter, type) VALUES (1, 'Accent', null, null, true, '610-13-019_ACC', 'HI-EXE IS42/IS47', 'headset', 'HST-ACCENT-HI-EXE-IS42-IS47', 'road', 'HI-EXE', 0.074, null, null, 47, 31.8, 42, 28.6, 'INTEGRATED');
INSERT INTO public.headset (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, bottom_frame_diameter, bottom_head_tube_diameter, top_frame_diameter, top_head_tube_diameter, type) VALUES (2, 'Accent', null, null, true, '610-13-050_ACC', 'HI-EVO TAPER', 'headset', 'HST-ACCENT-HI-EVO-TAPER', 'common', 'HI-EVO', 0.068, null, null, 52, 38.1, 42, 28.6, 'INTEGRATED');
INSERT INTO public.headset (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, bottom_frame_diameter, bottom_head_tube_diameter, top_frame_diameter, top_head_tube_diameter, type) VALUES (3, 'Accent', null, null, true, '610-13-000_ACC', 'HI-EXE', 'headset', 'HST-ACCENT-HI-EXE', 'common', 'HI-EXE', 0.072, null, null, 42, 28.6, 42, 28.6, 'INTEGRATED');

INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (5, 'Shimano', null, null, true, 'HB-M8110', 'M8110', 'hub', 'HUB-SHIMN-F-M8110', 'MTB', 'XT', 0.142, null, null, '100x15', 'E-THRU', 'center lock', null, 32, null, null, 5.7, 44, 44, 12, 60.2, 'front');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (3, 'Shimano', null, null, true, 'FH-M8130-B', 'M8130-B', 'hub', 'HUB-SHIMN-R-M8130-B', 'MTB', 'XT', 0.310, null, null, '157x12', 'E-THRU', 'center lock', null, 32, 'micro-spline', null, 6.43, 58, 61, 12, 72.69, 'rear');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (2, 'Shimano', null, null, true, 'FH-M8110-B', 'M8110-B', 'hub', 'HUB-SHIMN-R-M8110-B', 'MTB', 'XT', 0.307, null, null, '148x12', 'E-THRU', 'center lock', null, 32, 'micro-spline', null, 6.6, 60, 61, 12, 62.16, 'rear');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (1, 'Shimano', null, null, true, 'FH-M8110', 'M8110', 'hub', 'HUB-SHIMN-R-M8110', 'MTB', 'XT', 0.305, null, null, '142x12', 'E-THRU', 'center lock', null, 32, 'micro-spline', null, 6.72, 61, 61, 12, 55.17, 'rear');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (4, 'Shimano', 'for straight spokes', null, true, 'FH-M8110-BS', 'M8110-BS', 'hub', 'HUB-SHIMN-R-M8110-BS', 'MTB', 'XT', 0.306, null, null, '148x12', 'E-THRU', 'center lock', null, 32, 'micro-spline', null, 6.78, 45, 61, 12, 55.95, 'rear');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (6, 'Shimano', null, null, true, 'HB-M8110-B', 'M8110-B', 'hub', 'HUB-SHIMN-F-M8110-B', 'MTB', 'XT', 0.147, null, null, '110x15', 'E-THRU', 'center lock', null, 32, null, null, 5.7, 44, 44, 12, 70.2, 'front');
INSERT INTO public.hub (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, axle_diameter, axle_type, disc_type, freewheel_width, holes, hub_type, offset_left, offset_right, pcd_left, pcd_right, speeds, flange_distance, side) VALUES (7, 'Shimano', 'for straight spokes', null, true, 'HB-M8110-BS', 'M8110-BS', 'hub', 'HUB-SHIMN-F-M8110-BS', 'MTB', 'XT', 0.158, null, null, '110x15', 'E-THRU', 'center lock', null, 32, null, null, 3.7, 45, 45, 12, 62.8, 'front');

INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (2, 'Shimano', null, null, true, 'PD-M540', 'M540', 'pedals', 'PDL-SHIMN-M540', 'MTB', 'COMMON', 0.354, null, null, 'shimano-mtb', true, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (1, 'Shimano', null, null, true, 'PD-M520', 'M520', 'pedals', 'PDL-SHIMN-M520', 'MTB', 'COMMON', 0.382, null, null, 'shimano-mtb', true, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (3, 'Shimano', null, null, true, 'PD-M9100', 'M9100', 'pedals', 'PDL-SHIMN-M9100', 'MTB', 'XTR', 0.310, null, null, 'shimano-mtb', true, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (4, 'Shimano', null, '4550170444181', true, 'PD-M8100', 'M8100', 'pedals', 'PDL-SHIMN-M8100', 'MTB', 'XT', 0.342, null, null, 'shimano-mtb', true, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (5, 'Shimano', null, null, true, 'PD-M8120', 'M8120', 'pedals', 'PDL-SHIMN-M8120', 'MTB', 'XT', 0.438, null, null, 'shimano-mtb', true, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (6, 'Shimano', null, null, true, 'PD-M8140', 'M8140', 'pedals', 'PDL-SHIMN-M8140', 'MTB', 'XT', null, null, null, null, false, null);
INSERT INTO public.pedals (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, block, spd, type) VALUES (7, 'Crank Brothers', null, null, true, null, 'Egg Beater 1', 'pedals', 'PDL-CRBRO-EGGBEAT1', 'MTB', null, 0.256, null, null, 'crank-brothers-mtb', true, null);

INSERT INTO public.profile (id, email, password, username) VALUES (1, 'drzewieckifilip@gmail.com', '{bcrypt}$2a$10$QIuQh5LvvZATDS4.VtBe0OOmut8ii47Y9Zco0NVbLVnJTQIaZoiMW', 'veysenhof');

INSERT INTO public.rear_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cage, capacity, max_gears, max_sprocket, min_sprocket, speeds) VALUES (1, 'Shimano', null, null, true, 'RD-M8100-GS', 'M8100-GS', 'rearDerailleur', 'RDR-SHIMN-M8100-GS', 'MTB', 'XT', null, null, null, 'medium', 35, 1, 45, 10, 12);
INSERT INTO public.rear_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cage, capacity, max_gears, max_sprocket, min_sprocket, speeds) VALUES (2, 'Shimano', null, null, true, 'RD-M8100-SGS', 'M8100-SGS', 'rearDerailleur', 'RDR-SHIMN-M8100-SGS', 'MTB', 'XT', 0.284, null, null, 'long', 41, 1, 51, 10, 12);
INSERT INTO public.rear_derailleur (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cage, capacity, max_gears, max_sprocket, min_sprocket, speeds) VALUES (3, 'Shimano', null, null, true, 'RD-M8120-SGS', 'M8120-SGS', 'rearDerailleur', 'RDR-SHIMN-M8120-SGS', 'MTB', 'XT', 0.290, null, null, 'long', 45, 2, 45, 10, 12);

INSERT INTO public.role (id, role_name) VALUES (1, 'ADMIN');
INSERT INTO public.role (id, role_name) VALUES (2, 'CUSTOMER');

INSERT INTO public.saddle (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, length, material, width) VALUES (1, 'Accent', null, null, true, '610-08-99_ACC', 'Evo carbon', 'saddle', 'SDL-ACCENT-EVO-CARBON', 'common', 'Evo', 0.150, null, null, 275, 'carbon', 130);

INSERT INTO public.seatpost (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cable_route_type, diameter, length, material, seatpost_offset, suspension, travel) VALUES (1, 'Accent', null, null, true, null, 'Evo carbon offset', 'seatpost', 'SPT-ACCNT-EVOCARBON-31', 'common', 'Evo', 0.205, null, null, null, 31.6, null, 'carbon', 20, false, null);
INSERT INTO public.seatpost (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, cable_route_type, diameter, length, material, seatpost_offset, suspension, travel) VALUES (2, 'Accent', null, null, true, null, 'Evo carbon offset', 'seatpost', 'SPT-ACCNT-EVOCARBON-27', 'common', 'Evo', 0.205, null, null, null, 27.2, null, 'carbon', 20, false, null);

INSERT INTO public.shifter (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, brake_type, integrated_brake, shifts, side, speeds) VALUES (1, 'Shimano', null, null, true, 'SL-M8100-R', 'M8100-R', 'shifter', 'SHF-SHIMN-M8100R', 'MTB', 'XT', 0.117, null, null, null, false, '12', 'right', 12);
INSERT INTO public.shifter (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, brake_type, integrated_brake, shifts, side, speeds) VALUES (2, 'Shimano', null, null, true, 'SL-M8100-L', 'M8100-L', 'shifter', 'SHF-SHIMN-M8100L', 'MTB', 'XT', 0.078, null, null, null, false, '2', 'left', 12);
INSERT INTO public.shifter (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, brake_type, integrated_brake, shifts, side, speeds) VALUES (4, 'Shimano', 'I-spec EV', null, true, 'SL-M8100-IL', 'M8100-IL I-SPEC', 'shifter', 'SHF-SHIMN-M8100IL', 'MTB', 'XT', 0.078, null, null, null, false, '2', 'left', 12);
INSERT INTO public.shifter (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, brake_type, integrated_brake, shifts, side, speeds) VALUES (3, 'Shimano', 'I-spec EV', null, true, 'SL-M8100-IR', 'M8100-IR I-SPEC', 'shifter', 'SHF-SHIMN-M8100IR', 'MTB', 'XT', 0.120, null, null, null, false, '12', 'right', 12);

INSERT INTO public.stem (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, angle, handlebar_diameter, headtube_diameter, length) VALUES (1, 'Accent', null, null, true, null, 'Exe long', 'stem', 'STM-ACCNT-EXELONG-90', 'common', 'Exe', 0.129, null, null, 6, 31.8, 28.6, 90);
INSERT INTO public.stem (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, angle, handlebar_diameter, headtube_diameter, length) VALUES (2, 'Accent', null, null, true, null, 'Exe long', 'stem', 'STM-ACCNT-EXELONG', 'common', 'Exe', 0.129, null, null, 6, 31.8, 28.6, 100);
INSERT INTO public.stem (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, angle, handlebar_diameter, headtube_diameter, length) VALUES (3, 'Accent', null, null, true, null, 'Exe long', 'stem', 'STM-ACCNT-EXELONG-110', 'common', 'Exe', 0.129, null, null, 6, 31.8, 28.6, 110);

INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (1, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-28', 'road', 'Grand Prix', 0.240, null, null, 622, '3/330 TPI', false, null, 28);
INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (2, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-25', 'road', 'Grand Prix', 0.225, null, null, 622, '3/330 TPI', false, null, 25);
INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (3, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-23', 'road', 'Grand Prix', 0.200, null, null, 622, '3/330 TPI', false, null, 23);
INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (5, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-32-TR', 'road', 'Grand Prix', 0.375, null, null, 622, '3/180 TPI', true, null, 32);
INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (4, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-28-TR', 'road', 'Grand Prix', 0.315, null, null, 622, '3/180 TPI', true, null, 28);
INSERT INTO public.tyre (id, brand, comment, ean, is_official, manufacturers_code, model, product, product_id, purpose, series, weight, year, user_id, diameter, tpi, tubeless, type, width) VALUES (6, 'Continental', null, null, true, null, 'Grand Prix 5000', 'tyre', 'TYR-CONTI-GP5000-25-TR', 'road', 'Grand Prix', 0.295, null, null, 622, '3/180 TPI', true, null, 25);





























